apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tilt_gameserver_id
  namespace: tilt_namespace
  labels:
    app: tilt_gameserver_id
spec:
  serviceName: gameserver
  selector:
    matchLabels:
      app: tilt_gameserver_id
  replicas: 1
  template:
    metadata:
      labels:
        app: tilt_gameserver_id
    spec:
      containers:
        - name: tilt_gameserver_id
          image: "localhost:5005/mystic/gs"
          ports:
            - containerPort: 9050
              protocol: UDP
          env:
            - name: OTEL_SERVICE_NAME
              value: "gameserver"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://monitoring-signoz-otel-collector.platform.svc.cluster.local:4317
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=tilt_namespace,service.instance.id=tilt_gameserver_id"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tilt_gameserver_id
  namespace: tilt_namespace
spec:
  selector:
    app: tilt_gameserver_id
  type: NodePort
  ports:
    - name: tilt_gameserver_id
      protocol: UDP
      port: 9050
      nodePort: tilt_port
